_target_: src.models.recog_module.RegLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

num_classes : 2

net : 
  _target_: src.models.components.recognizerCf.SimpleRecog
  config_file: 'mmaction2/configs/recognition/tsn/tsn_imagenet-pretrained-r50_8xb32-1x1x3-100e_kinetics400-rgb.py'
  num_classes: 2
  checkpoint_file : "tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth"